Interaction System Documentation
RE-SS3D/SS3D pull request #1052
Opened 2023-03-01 16:02 UTC by TaylorNAlbarnaz

## Summary

Documents the remaining classes, interfaces and methods that weren't properly documented

## Changes to Files

Changes pretty much every script in the SS3D/Interactions folder, only additions were comments, and a single unused "InteractionInvalid" event was removed

2023-03-01 18:17 UTC, cosmiccoincidence commented
Please link the documentation in the PR description.

2023-03-02 17:49 UTC, stilnat requested changes, later dismissed
just a small correction and good to go

2023-03-02 17:49 UTC, stilnat commented on Assets/Scripts/SS3D/Interactions/InteractionTargetNetworkBehaviour.cs
> +    /// A base class for interaction targets which use the mirror NetworkBehaviour
correct that to fishnet

2023-03-03 22:25 UTC, cosmiccoincidence approved these changes
Looks good.

2023-03-03 22:26 UTC, merged