Actor rework
RE-SS3D/SS3D pull request #1065
Opened 2023-03-04 00:02 UTC by joaoburatto

## Summary

Reworks the whole Actor system to improve QOL and document long forgotten parts of that code.

2023-03-05 09:04 UTC, stilnat commented
I won't take the responsibility to review this one. It's lacking a proper description, it's way too big, and many changes are not explained at all. A single sentence is clearly not enough to understand what's going on and why we even need that. As it is, I think merging it is a bad idea.

2023-03-07 10:56 UTC, cosmiccoincidence commented
Is this PR meant to complete #1009 ??

2023-03-07 10:59 UTC, joaoburatto commented
> Is this PR meant to complete #1009 ??

Good catch, I did not remembered I had created that one. Yes it does close it.

2023-03-07 12:22 UTC, joaoburatto commented
> I won't take the responsibility to review this one. It's lacking a proper description, it's way too big, and most of the changes are not explained at all. A single sentence is clearly not enough to understand what's going on and why we even need that. As it is, I think merging it is a bad idea.
> 
> What I expect before reviewing :
> 
> * Detailed account of the issues of the modified files, along with the proposed solution.
> * Why do we need what was added.
> * At the very least, every public class, structure, interface with a summary. Not talking about methods and fields.
> * Remove the renaming so I can focus on what matters, make a PR for renaming.
> 
> We also already discussed about renaming stuff in a PR. This make the review process tedious as more than half the changes are just renaming, but the reviewer still has to be careful about it.

Updated the description. The renaming is a part of this PR.

2023-03-07 20:04 UTC, stilnat requested changes
A few questions, a few comments, nothing much to add.

2023-03-07 20:04 UTC, stilnat commented on Assets/Scripts/SS3D/Core/Behaviours/Actor.cs
> -        public Transform TransformCache
why is that removed ?

2023-03-07 20:04 UTC, stilnat commented on Assets/Scripts/SS3D/Core/Behaviours/Actor.cs
> +    public class Actor : ActorBase, IActor
please add a few lines to explain how it optimises Monobehaviour.

2023-03-07 20:04 UTC, stilnat commented on Assets/Scripts/SS3D/Core/Behaviours/NetworkActor.cs
> +    /// Used to optimize all GameObjects, avoid MonoBehaviours
please add a few lines to explain how it optimises NetworkBehaviour.

2023-03-07 20:04 UTC, stilnat commented on Assets/Scripts/SS3D/Systems/Gamemodes/UI/GamemodeObjectivePanelView.cs
> +        private void ProcessInput()
shouldn't that use the new input system ?

2023-03-07 20:04 UTC, stilnat commented on Assets/Scripts/SS3D/Systems/Roles/RoleSystem.cs
> +    public class RoleSystem : NetworkSubsystem
rename to roleSubSystem for consistency.

2023-03-07 20:37 UTC, joaoburatto commented on Assets/Scripts/SS3D/Core/Behaviours/Actor.cs
> -        public Transform TransformCache
Moved to `ActorBase.cs`

2023-03-07 20:38 UTC, joaoburatto commented on Assets/Scripts/SS3D/Systems/Gamemodes/UI/GamemodeObjectivePanelView.cs
> +        private void ProcessInput()
Unrelated to this PR. Only changed due to Actor changes.

2023-03-07 22:19 UTC, stilnat commented
fix that stuff : 
![image](https://user-images.githubusercontent.com/14344825/223566607-5cb4aae7-6989-4d38-be2a-9848982d3180.png)

2023-03-10 02:02 UTC, cosmiccoincidence commented
We're the errors fixed? Is this ready for another review @joaoburatto ?

2023-03-12 18:55 UTC, cosmiccoincidence commented
lgtm

2023-03-13 08:22 UTC, stilnat requested changes
Some new issues : Looks like the material for ghost construction stuff is out 
![image](https://user-images.githubusercontent.com/14344825/224645395-02c457bc-11e2-4c68-bff6-5fae4ed4b985.png)

it broke something on the interaction system, I can't interact with some stuff anymore. Issues are not limited to the toolbox : 
![image](https://user-images.githubusercontent.com/14344825/224645638-79064bde-7a86-4532-b0a8-0a2a2af33443.png)

2023-03-18 21:07 UTC, stilnat commented
This PR modifies half the scripts of our repo, some changes are pretty significant, some were breaking systems, and although resolved, I can't give any guarantee that some of those other changes are not harmful. My advice on this one is, close the PR, port only the relevant change on another one, please remove the renaming, it just affect too many files and it's painful to review when one has to be careful if it's really only renaming. Open a PR for renaming only after. I'm keeping "request changes" for now because I don't want it to be accidentally merged but if someone wants to review it, let me know if you approve it and I'll remove the request changes.

2023-03-18 21:11 UTC, stilnat commented
Among the issues still present on this PR
- can catch items from the other side of the map
- materials in tilemap editor menu are absent (everything's purple)

2023-03-20 10:09 UTC, stilnat commented
Why I believe this PR should not be merged : 

1. most changes are completely unrelated to the PR's topic, actor's improvement.
2. A few changes, completely unrelated to the PR's topic, were game breaking and a few more could be that were not spotted.
3. It's making very hard to identify what commit caused what bugs since it's so big, making future debugging painful.
4. John made important changes to systems he himself said know almost nothing about such as the inventory system and the UI around it.
5. It modifies code style in ways we did not agree upon collectively, check attachedcontainer.cs as an example, attributes are on two different lines in this PR, when they were on a single line previously. It's an arbitrary choice, not relying on our C# style guide, and it's very debatable if that's actually something we want. 
6. It's making it hard to focus on the actual point of the PR, improving actors. After all the time I spent on that, I still have no idea how it improves it really since I had to deal with all the unwanted changes.
7. It shuffle files and folders around with no explanations.

All in all, I feel like this PR is way, way below our standards, it's making everyone lose time, fixing bugs that should not exist in the first place, it lacks explanation on most of the changes, it's compromising our chances to relate a bug to a given commit, it's not well tested, and it's hard to understand. 

If John didn't try to modify half the repository, this would be probably merged after 3 commits and some discussions about the actual improvement. What frustrate me the most is, that this probably contains actual improvement.

Just to be very clear about this, I tried to stay as factual as possible, my only care is the well being of the game. Some of this might sounds harsh and it is, but as the lead dev, I have higher expectation for John than for other contributors. I would not let that PR pass for any other contributors, so I've no reason to do it for John.

That said, if another reviewer wants to merge it, I'll accept it too, but not before asking them if they read this beforehand, as I want them to fully understand the issues with merging this kind of PR.

2023-03-21 10:44 UTC, closed without merging