Dispose components on death
RE-SS3D/SS3D pull request #1157
Opened 2023-03-31 02:26 UTC by xk0fe

## Summary
Dispose hands, inventory and interactions also hide inventory for ghost ([reference](https://www.youtube.com/watch?v=45ryS19cNy4))

## Technical Notes (optional)

## Known issues
Issues below were present before the PR
* Player's body is floating above the ground after the rotation is applied to it,
* If the match restarts player can't walk on spawn

## Fixes (optional)
#991

2023-03-31 11:09 UTC, joaoburatto requested changes, later dismissed

2023-03-31 11:09 UTC, joaoburatto commented on Assets/Scripts/SS3D/Systems/Health/HealthController.cs
> +        originEntityGameObject.GetComponent<HumanoidController>().Dispose(true);
I'm fine with this for now. But please add a comment saying it is a temporary solution and it has to be optimized later on using a `TODO:` tag, like:
`TODO: Optimize these GetComponents, this is a temporary solution.`

2023-03-31 11:09 UTC, joaoburatto commented on Assets/Scripts/SS3D/Systems/Health/HealthController.cs
> +        Transform originEntityTransform = originEntity.transform;
You don't need to cache the transform, we already have that inside the NetworkActor class. You can have something like:

```
ghostEntity.Transform.SetPositionAndRotation(originEntityTransform.position, originEntityTransform.rotation);
originEntity.Transform.Rotate(new Vector3(90, 0, 0));
```

2023-03-31 11:09 UTC, joaoburatto commented on Assets/Scripts/SS3D/Systems/Interactions/InteractionController.cs
> +            if (!Owner.IsLocalClient) return;
add a space or brackets to not clutter these lines

2023-03-31 13:56 UTC, xk0fe commented
Thanks! I've updated PR according to request

2023-04-01 17:16 UTC, stilnat approved these changes
tested on host and client, working fine, good code, good to go

2023-04-01 18:44 UTC, merged