[WIP] Play mode tests
RE-SS3D/SS3D pull request #1168
Opened 2023-04-07 23:03 UTC by stilnat

## Summary

Taking back Ryan's work to have in game play mode tests

## Pictures/Videos (optional)

## Changes to Files

## Technical Notes (optional)

## Known issues

## Fixes (optional)

2023-04-28 14:47 UTC, cosmiccoincidence commented
High priority because at least 2 other PRs are waiting for this one to be merged first.

2023-05-01 20:57 UTC, joaoburatto requested changes, later dismissed

2023-05-01 20:57 UTC, joaoburatto commented on Assets/Scripts/Tests/Common/SpessEditModeTest.cs
> +    public abstract class SpessEditModeTest: SpessTest
Remove the `Spess` prefix, its cool but its better to avoid funny stuff.

2023-05-01 20:57 UTC, joaoburatto commented on Assets/Scripts/Tests/Common/SpessTest.cs
> +    public abstract class SpessTest
Remove the `Spess` prefix, its cool but its better to avoid funny stuff. If the Test name conflicsts with something maybe try `UnitTest`

2023-05-04 07:31 UTC, cosmiccoincidence commented
What's the hold up here?

2023-05-05 08:59 UTC, stilnat commented
@cosmiccoincidence someone other than contributors to it need to test it a bit.

2023-05-05 17:00 UTC, cosmiccoincidence commented
Fair. I would review it but I don't know much about testing or how to run them. I would just end up having to ask of the contributors about it and basically follow some steps given to me by them, which doesn't seem much better or different even.

I see that this was started by Ryan and then finished by you, has Ryan taken a look at this recently? If the two of you think it's good I would be satisfied with that. Having a 3rd party look at would be nice but if Ryan takes a look then we already have 2 sets of eyes on it, both of which with Maintainer privileges.

Also consider writing a guide on how to run the tests on the GitBook maintainer guide.

2023-05-05 22:22 UTC, stilnat commented
I'll add doc once merged. I don't think Ryan took a look at this recently no, but most of it is Ryan's work, I simplified it a bit.

2023-05-14 17:04 UTC, cosmiccoincidence requested changes
Resolve conflict please

2023-05-15 20:04 UTC, stilnat commented
Closed for now, to allow moving forward on other part of the code base.

2023-09-12 18:58 UTC, stilnat commented
Fixed, and updated to work with the current build.
All play tests should pass.

2023-09-27 20:36 UTC, cosmiccoincidence commented
I would review this but I am unfamiliar with the testing "system" that is already implemented and ultimately don't know exactly how to run these tests in order to properly review the PR.

2023-09-27 20:40 UTC, stilnat commented
@cosmiccoincidence my request was more to let you know your previous request can be dismissed. However that made me think I should add a step by step guide to use it, so I'll do that.

2023-09-27 20:45 UTC, cosmiccoincidence approved these changes, later dismissed

2023-10-09 22:22 UTC, cosmiccoincidence approved these changes
Works as expected. Wish someone could have looked at the code a bit more but it's time this get merged already.

Don't forget to document this on gitbook.

2023-10-09 22:23 UTC, merged