rename code, prefabs, gameObjects, inputs
RE-SS3D/SS3D pull request #1191
Opened 2023-04-29 00:01 UTC by xk0fe

## Summary
Renamed soul to player, mind to character
Tests ok, no errors on play

## Changes to Files
- added a todo in `CharacterSystem.TryGetCharacter` for further inspection of the code
- changed `originalSoul`, `targetSoul` to `originalCharacter`, `targetCharacter` in `CharacterSystem.SwapCharacters` these were obviously are typos
- changed `an user` to `a user` in comments to methods somewhere in the code i dont remember

Also changes in prefabs (Soul; Mind), inputs and Lobby scene

## Known issues
Will cause merge conflicts #1185 #1168

## Fixes (optional)
Closes #1176

2023-04-30 23:33 UTC, cosmiccoincidence commented
Due to the merge conflicts, were going to wait to merge this until after the others. So this may sit open for a week or so in the meantime, even after it receives an accepted review.

2023-05-15 22:20 UTC, joaoburatto commented
Mind renaming back Character to Mind? I think we can still use the Mind naming.

2023-05-16 14:29 UTC, xk0fe commented
> Mind renaming back Character to Mind? I think we can still use the Mind naming. I can do it if you give me access to your branch.

Done

2023-05-16 17:16 UTC, stilnat requested changes
A few style correction and all good. Good catch on the input bug with the mind swap. That's a very small fix in a mostly renaming PR so that's fine, but that could be worth a small PR of its own.

2023-05-16 17:16 UTC, stilnat commented on Assets/Scripts/SS3D/Systems/Entities/MindSystem.cs
> +        private Mind emptyMind;
private members should have the "_" prefix, please put that back.

2023-05-16 17:16 UTC, stilnat commented on Assets/Scripts/SS3D/Systems/IngameConsoleSystem/Commands/ItemCommands/ItemCommandUtilities.cs
> +            Player playerPlayer = playerSystem.GetPlayer(LocalPlayer.Ckey);
rename that to simply "player"

2023-05-16 17:16 UTC, stilnat commented on Assets/Scripts/SS3D/Systems/PlayerControl/PlayerSystem.cs
> +        private Player playerPrefab;
add the "_" prefix "_playerPrefab"

2023-05-16 21:45 UTC, xk0fe commented
> A few style correction and all good
Done

2023-05-16 21:50 UTC, stilnat approved these changes
Looks good to me

2023-05-16 21:55 UTC, merged