Smoother embark and game screens refactor
RE-SS3D/SS3D pull request #1213
Opened 2023-06-07 12:04 UTC by joaoburatto

## Summary

This PR reworks how the game screens work internally, adds a fade out when the player enters the game, creates a ScriptableSettings script to define how general UI works. Reorder objects around the game scene, and creates prefabs from a few objects on the game scene.

2023-06-13 19:14 UTC, cosmiccoincidence requested changes, later dismissed
The following files need to be renamed to PascalCase:
- Player Camer.prefab
- Static World Objects.prefab
- Black Overlay.prefab
- Canvas Template.prefab
- Networked View.prefab

2023-07-22 21:27 UTC, stilnat requested changes
A few changes to do, seems to work fine with host (I need to mess around more), not tested with client yet. Also need to check if there's conflict with the inventory rework, probably minor ones but please let's do that before any merge, I don't my whole work wasted.

2023-07-22 21:27 UTC, stilnat commented on Assets/Scripts/SS3D/Systems/Screens/GameScreens.cs
> +    public static class GameScreens
For the sake of clarity, it'd be nice if you could add the [Server] [Client] [ServerOrClient] attributes on relevant methods. That way we understand better what execute what and it limits error due to server or client calling methods they're not supposed to.

2023-07-22 21:27 UTC, stilnat commented on Assets/Scripts/SS3D/Systems/Screens/GameScreen.cs
> +        public ScreenType ScreenType;
Should this stay private ?

2023-07-22 21:27 UTC, stilnat commented on Assets/Scripts/SS3D/Systems/Entities/UI/PlayerCameraBlockerView.cs
> +namespace SS3D.Systems.Entities.UI
What's this script for, please add comments

2023-07-23 18:49 UTC, stilnat commented
Client breaks the container UI, please check if this happen on develop already, and if not, please fix before merge 
![image](https://github.com/RE-SS3D/SS3D/assets/14344825/51979c84-3c34-4bdb-be8f-8942293c169d)

2023-07-25 12:04 UTC, stilnat approved these changes
good to go

2023-07-26 07:50 UTC, merged