Runtime inspector, runtime hierarchy and Inspector plus plugins
RE-SS3D/SS3D pull request #1224
Opened 2023-07-05 06:18 UTC by Mechar418

Implement inspector and hierarchy in development builds. <kbd>I</kbd> opens and closes inspector and hierarchy window.
Implement Inspector plus for unity editor
https://github.com/yasirkula/UnityRuntimeInspector
https://github.com/yasirkula/UnityInspectPlus
![изображение](https://github.com/RE-SS3D/SS3D/assets/77565416/20c7f9b1-219a-4d23-bd8f-35affdb252ef)

2023-07-05 19:04 UTC, joaoburatto commented
Is there a reason for this? I don't mind adding, but I don't want to add tools just to add tools

2023-07-05 19:28 UTC, iamteapot422 commented
@joaoburatto well, i find it very useful. Runtime inspector saves time on debugging, and inspector plus makes working with several objects comfortable. Ive asked about these plugins on discord and @stilnat said that he would like to see the plugins in the project.

2023-07-05 19:59 UTC, stilnat commented
@joaoburatto it's useful to debug client outside of editor at the same time as the host, when it comes to stuff such as checking hierarchy of game objects and stuff. Much more convenient than any code debugging solution for some specific cases imo.

2023-07-08 06:51 UTC, stilnat requested changes
I get two compiler errors :

- Assembly with name 'RuntimeInspector.Runtime' already exists (Assets/Plugins/RuntimeInspector/RuntimeInspector.Runtime.asmdef)
- Assembly with name 'RuntimeInspector.Runtime' already exists (Assets/Scripts/External/RuntimeInspector/RuntimeInspector.Runtime.asmdef)

2023-07-10 08:57 UTC, iamteapot422 commented
@stilnat can't replicate, plugins folder shouldn't exist. Try deleting the folder and pulling the branch again

2023-07-10 13:30 UTC, stilnat commented
@iamteapot422 I can't figure how it works, pressing i does nothing for me, does it works on your side ?

2023-07-10 14:29 UTC, iamteapot422 commented
@stilnat do you test it on a developer build?

2023-07-10 14:39 UTC, stilnat approved these changes
working, useful addition, good work

2023-07-10 14:39 UTC, merged