[WIP] Simple crafting system
RE-SS3D/SS3D pull request #1260
Opened 2023-09-18 22:26 UTC by stilnat

## Summary

Simple item replacement crafting, as described on gitbook : 
https://ss3d.gitbook.io/design/actions/crafting/makeshift-crafting

System is mostly functionnal, does not include "steps" in the recipe for now, it's a simple item replacement.
However, it can handle arbitrary complex recipes. 

A recipe is made of a crafting interaction (screw, slice, hammer...), a target (the item on which to apply the interaction), and a list of items and the needed count for each item.

The crafting interaction is only available when all conditions are present : 
- The right target
- The right items needed in the right amount
- The right interaction (so a tool able to produce it) 

Items counted as available are items in close proximity from the target item. So to get the crafting interaction available, for now you have to drop all necessary items close to the target item.

The system works when other close items are not part of the recipe as well. 

It currently consumes all crafting ressources and spawn the product of the recipe. It's currently an instant interaction (no delay). 

## Changes to Files

## Technical Notes (optional)

## Known issues

## Fixes (optional)

2023-09-19 23:07 UTC, singulocity commented
To test, I spawned a knife, took off my hat, place it on the ground, then with the knife active, I clicked on it so that it would start the crafting. If I do nothing else, it works fine. If I walk away, it cancels which is great.

But I can pick up the hat while I am interacting with it with the knife. The recipe completes, the items spawn where the hat was in my hand and drop on the ground, and the hat is still maintained by the UI as being in my hand still.

Same thing if I put the hat in a pocket quickly.

Although while it was in my hand at least I could "drop" it to fix the state. Now it is stuck in my pocket forever. Haha.

We may need some kind of check to prevent players from picking up the thing they are interacting with.

2023-09-19 23:18 UTC, singulocity commented
Can't build to test host/client. Console log:
`Local server is starting for Tugboat.
UnityEngine.Debug:Log (object)
FishNet.Managing.Server.ServerManager:Transport_OnServerConnectionState (FishNet.Transporting.ServerConnectionStateArgs) (at Assets/FishNet/Runtime/Managing/Server/ServerManager.cs:498)
FishNet.Transporting.Tugboat.Tugboat:HandleServerConnectionState (FishNet.Transporting.ServerConnectionStateArgs) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:169)
FishNet.Transporting.Tugboat.CommonSocket:SetConnectionState (FishNet.Transporting.LocalConnectionState,bool) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Core/CommonSocket.cs:38)
FishNet.Transporting.Tugboat.Server.ServerSocket:StartConnection (uint16,int,string,string) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Core/ServerSocket.cs:279)
FishNet.Transporting.Tugboat.Tugboat:StartServer () (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:423)
FishNet.Transporting.Tugboat.Tugboat:StartConnection (bool) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:376)
FishNet.Managing.Server.ServerManager:StartConnection (uint16) (at Assets/FishNet/Runtime/Managing/Server/ServerManager.cs:328)
SS3D.Core.SessionNetworkSystem:InitializeNetworkSession () (at Assets/Scripts/SS3D/Core/SessionNetworkSystem.cs:47)
SS3D.Core.ApplicationInitializerSystem:InitializeNetworkSession () (at Assets/Scripts/SS3D/Core/ApplicationInitializerSystem.cs:109)
SS3D.Core.ApplicationInitializerSystem:InitializeApplication () (at Assets/Scripts/SS3D/Core/ApplicationInitializerSystem.cs:54)
SS3D.Core.Intro.IntroUIHelper:Setup () (at Assets/Scripts/SS3D/Core/Intro/IntroUIHelper.cs:41)
SS3D.Core.Intro.IntroUIHelper:Start () (at Assets/Scripts/SS3D/Core/Intro/IntroUIHelper.cs:29)

Local client is starting for Tugboat.
UnityEngine.Debug:Log (object)
FishNet.Managing.Client.ClientManager:Transport_OnClientConnectionState (FishNet.Transporting.ClientConnectionStateArgs) (at Assets/FishNet/Runtime/Managing/Client/ClientManager.cs:309)
FishNet.Transporting.Tugboat.Tugboat:HandleClientConnectionState (FishNet.Transporting.ClientConnectionStateArgs) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:161)
FishNet.Transporting.Tugboat.CommonSocket:SetConnectionState (FishNet.Transporting.LocalConnectionState,bool) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Core/CommonSocket.cs:40)
FishNet.Transporting.Tugboat.Client.ClientSocket:StartConnection (string,uint16) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Core/ClientSocket.cs:141)
FishNet.Transporting.Tugboat.Tugboat:StartClient (string) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:445)
FishNet.Transporting.Tugboat.Tugboat:StartConnection (bool) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:378)
FishNet.Managing.Client.ClientManager:StartConnection () (at Assets/FishNet/Runtime/Managing/Client/ClientManager.cs:264)
SS3D.Core.SessionNetworkSystem:InitializeNetworkSession () (at Assets/Scripts/SS3D/Core/SessionNetworkSystem.cs:48)
SS3D.Core.ApplicationInitializerSystem:InitializeNetworkSession () (at Assets/Scripts/SS3D/Core/ApplicationInitializerSystem.cs:109)
SS3D.Core.ApplicationInitializerSystem:InitializeApplication () (at Assets/Scripts/SS3D/Core/ApplicationInitializerSystem.cs:54)
SS3D.Core.Intro.IntroUIHelper:Setup () (at Assets/Scripts/SS3D/Core/Intro/IntroUIHelper.cs:41)
SS3D.Core.Intro.IntroUIHelper:Start () (at Assets/Scripts/SS3D/Core/Intro/IntroUIHelper.cs:29)

Local server is started for Tugboat.
UnityEngine.Debug:Log (object)
FishNet.Managing.Server.ServerManager:Transport_OnServerConnectionState (FishNet.Transporting.ServerConnectionStateArgs) (at Assets/FishNet/Runtime/Managing/Server/ServerManager.cs:498)
FishNet.Transporting.Tugboat.Tugboat:HandleServerConnectionState (FishNet.Transporting.ServerConnectionStateArgs) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:169)
FishNet.Transporting.Tugboat.CommonSocket:SetConnectionState (FishNet.Transporting.LocalConnectionState,bool) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Core/CommonSocket.cs:38)
FishNet.Transporting.Tugboat.Server.ServerSocket:IterateIncoming () (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Core/ServerSocket.cs:468)
FishNet.Transporting.Tugboat.Tugboat:IterateIncoming (bool) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:190)
FishNet.Managing.Transporting.TransportManager:IterateIncoming (bool) (at Assets/FishNet/Runtime/Managing/Transporting/TransportManager.cs:561)
FishNet.Managing.Timing.TimeManager:TryIterateData (bool) (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:1048)
FishNet.Managing.Timing.TimeManager:IncreaseTick () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:708)
FishNet.Managing.Timing.TimeManager:<TickUpdate>g__MethodLogic|104_0 () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:383)
FishNet.Managing.Timing.TimeManager:TickUpdate () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:373)
FishNet.Transporting.NetworkReaderLoop:Update () (at Assets/FishNet/Runtime/Transporting/NetworkReaderLoop.cs:28)

Local client is started for Tugboat.
UnityEngine.Debug:Log (object)
FishNet.Managing.Client.ClientManager:Transport_OnClientConnectionState (FishNet.Transporting.ClientConnectionStateArgs) (at Assets/FishNet/Runtime/Managing/Client/ClientManager.cs:309)
FishNet.Transporting.Tugboat.Tugboat:HandleClientConnectionState (FishNet.Transporting.ClientConnectionStateArgs) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:161)
FishNet.Transporting.Tugboat.CommonSocket:SetConnectionState (FishNet.Transporting.LocalConnectionState,bool) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Core/CommonSocket.cs:40)
FishNet.Transporting.Tugboat.Client.ClientSocket:IterateIncoming () (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Core/ClientSocket.cs:265)
FishNet.Transporting.Tugboat.Tugboat:IterateIncoming (bool) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:192)
FishNet.Managing.Transporting.TransportManager:IterateIncoming (bool) (at Assets/FishNet/Runtime/Managing/Transporting/TransportManager.cs:561)
FishNet.Managing.Timing.TimeManager:TryIterateData (bool) (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:1049)
FishNet.Managing.Timing.TimeManager:IncreaseTick () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:708)
FishNet.Managing.Timing.TimeManager:<TickUpdate>g__MethodLogic|104_0 () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:383)
FishNet.Managing.Timing.TimeManager:TickUpdate () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:373)
FishNet.Transporting.NetworkReaderLoop:Update () (at Assets/FishNet/Runtime/Transporting/NetworkReaderLoop.cs:28)

Reverting Startup Scene to ""
UnityEngine.Debug:Log (object)
Coimbra.Editor.EditorStartupSceneSettings:ConfigureStartupScene (UnityEditor.PlayModeStateChange) (at Library/PackageCache/com.coimbrastudios.core@11.0.5/Coimbra.Editor/EditorStartupSceneSettings.cs:72)
UnityEditor.EditorApplication:Internal_PlayModeStateChanged (UnityEditor.PlayModeStateChange)

Remote connection started for Id 0.
UnityEngine.Debug:Log (object)
FishNet.Managing.Logging.LevelLoggingConfiguration:Log (string) (at Assets/FishNet/Runtime/Managing/Logging/LevelLoggingConfiguration.cs:108)
FishNet.Managing.NetworkManager:Log (string) (at Assets/FishNet/Runtime/Managing/NetworkManager.Logging.cs:74)
FishNet.Managing.Server.ServerManager:Transport_OnRemoteConnectionState (FishNet.Transporting.RemoteConnectionStateArgs) (at Assets/FishNet/Runtime/Managing/Server/ServerManager.cs:524)
FishNet.Transporting.Tugboat.Tugboat:HandleRemoteConnectionState (FishNet.Transporting.RemoteConnectionStateArgs) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:178)
FishNet.Transporting.Tug [...]

2023-10-05 09:29 UTC, stilnat commented
Issues above spotted by @singulocity are fixed

2023-10-07 19:10 UTC, cosmiccoincidence requested changes
When play testing, the first recipe worked fine for me but the "weird complex recipe" did not. The target is a bike horn which also has it's own interaction when clicked, I noticed this is overriding the crafting interaction and preventing it from happening. Changing the target to something w/o any unique interactions and the recipe works fine. I suggest preventing the item's unique interactions from occurring when holding an item to fix this, as it doesn't make sense for me to honk the bikehorn if i click it with a knife.

2023-10-08 18:10 UTC, stilnat commented
@cosmiccoincidence  I simply added a condition for the honk interaction, stating you need a hand to honk (so won't happen when holding a knife). I'm afraid always overriding the interaction for all cases, might be a bad idea. I rather have each interaction handle that on their own. Fixed the issue for the bikehorn.

2023-10-09 01:56 UTC, cosmiccoincidence commented
> @cosmiccoincidence I simply added a condition for the honk interaction, stating you need a hand to honk (so won't happen when holding a knife). I'm afraid always overriding the interaction for all cases, might be a bad idea. I rather have each interaction handle that on their own. Fixed the issue for the bikehorn.

I'm not sure I agree. Imo I think the default interaction for an empty hand should be to grab the item, but if the hand has something held the interaction would be to use the held item on the target. I don't think people will use interactions on Items without grabbing them first very often. And if they do, they can easily right click it.

2023-10-09 10:09 UTC, stilnat commented
@cosmiccoincidence  the default interaction is still picking up. Just try and test and let me know how this feels, I think it'll be the way you wanted.

2023-10-09 23:12 UTC, cosmiccoincidence submitted a review, later dismissed

2023-10-09 23:15 UTC, cosmiccoincidence approved these changes

2023-10-09 23:15 UTC, merged