Expand permissions system
RE-SS3D/SS3D pull request #1267
Opened 2023-09-26 18:37 UTC by joaoburatto

## Summary

Expand the permission system to add the ChangePermission method and save permissions when they are changed. Also added an option to add the server owner permission to the host. I also moved the permission system to a separate assembly

2023-10-08 11:41 UTC, stilnat requested changes
Just a bit of doc to add, and explain a bit more how this works from the user perspective in the PR description. Do I choose to register permission ? Is is automatic ? Can you do it on build or only in editor ?

2023-10-08 11:41 UTC, stilnat commented on Assets/Scripts/SS3D/Permissions/PermissionSettings.cs
> +    public class PermissionSettings : ScriptableSettings
Add some doc

2023-10-08 11:41 UTC, stilnat commented on Assets/Scripts/SS3D/Permissions/PermissionSystem.cs
> +        public void SaveUserPermissions()
add some doc

2023-10-10 15:43 UTC, joaoburatto commented on Assets/Scripts/SS3D/Permissions/PermissionSettings.cs
> +    public class PermissionSettings : ScriptableSettings
Added

2023-10-10 15:43 UTC, joaoburatto commented on Assets/Scripts/SS3D/Permissions/PermissionSystem.cs
> +        public void SaveUserPermissions()
Added

2023-10-15 22:44 UTC, stilnat requested changes
Please add a detailed description of the PR

2023-10-17 02:45 UTC, joaoburatto commented
@stilnat added docs and description

2023-10-18 17:59 UTC, stilnat requested changes
fix build error

2023-10-29 20:48 UTC, stilnat approved these changes
works as expected, good job

2023-10-29 20:48 UTC, merged