Reworks asset data and improves role system
RE-SS3D/SS3D pull request #1268
Opened 2023-09-27 17:48 UTC by joaoburatto

## Summary

This PR reworks the asset data system to not rely on Enums anymore, we now use a DatabaseAsset to recognize each asset and know what to grab. Also has some handy methods to access it easily.

Also improves the role system to ease out the loadout setup process.

## Changes to Files

The asset data system has been modified a lot.

## Technical Notes (optional)

I gitignored generated scripts, to not induce a ton of conflicts.

## Known issues

Something might be broken. I haven't tested every scenario

2023-09-29 09:26 UTC, stilnat requested changes
did not review the code yet, in the meantime, needs : 
- documentation on how to use it (in code and how to create new database and whatever is needed to use it).
- To wait for older PRs using the old asset managment system to be properly reviewed (whether rejected or accepted)
- Should make asset managment simpler and therefore close #1259.
- Should make sure it doesn't have the issue of #1136 and therefore closing it.

2023-10-15 07:58 UTC, stilnat requested changes
Partial review, just one question for now : 

What happen if I change the name of an asset and regenerate the database ?

2023-10-15 07:58 UTC, stilnat commented on Assets/Scripts/SS3D/Systems/Inventory/Items/Item.cs
> -            if(!Enum.TryParse(itemName, out ItemId id))
replace this check instead of removing it

2023-10-15 07:58 UTC, stilnat commented on Assets/Scripts/SS3D/SceneManagement/Editor/EditorSceneUtils.cs
> +        public static void StartScene(string sceneName)
indentation issue

2023-10-15 07:58 UTC, stilnat commented on Assets/Scripts/SS3D/SceneManagement/Editor/SceneSwitcher.cs
> +					EditorSceneUtils.StartScene("sceneEnum");
where's that "sceneEnum" string defined ?

2023-10-17 03:03 UTC, joaoburatto commented
> Partial review, just one question for now :
> 
> What happen if I change the name of an asset and regenerate the database ?

Currently nothing, I plan to add cleanup when things are removed.

2023-10-17 16:49 UTC, cosmiccoincidence commented
250 file changes is a lot. In the future I would recommend trying to separate the PR into 2-3 pieces if possible to making reviewing easier.

2023-10-17 16:51 UTC, joaoburatto commented
> 250 file changes is a lot. In the future I would recommend trying to separate the PR into 2-3 pieces if possible to making reviewing easier.

I'm trying to tackle structural issues as soon as possible. There are many changes because this system is used project-wide, there was no escape from that damage lol.

2023-10-18 18:17 UTC, stilnat requested changes
Partial review : seems like the crafting system is broken.  I should see a slice interaction there.
![image](https://github.com/RE-SS3D/SS3D/assets/14344825/17b11eec-86f1-4373-a372-b346a5d815b8)

2023-10-18 18:17 UTC, stilnat commented on Assets/Scripts/SS3D/CodeGeneration/Creators/DatabaseAssetCreator.cs
> +        /// Creates an enum in the object path, with the defined enum name and using a list of provided assets as its elements.
is it an enum ? I see a collection of strings ?

2023-10-18 18:17 UTC, stilnat commented on Assets/Scripts/SS3D/CodeGeneration/Creators/EnumCreator.cs
> +            enumerable.Insert(0, "None");
What's that for ? the insert none.

2023-10-18 18:17 UTC, stilnat commented on Assets/Scripts/SS3D/CodeGeneration/Creators/StaticClassCreator.cs
> +        /// Creates an enum in the object path, with the defined enum name and using a list of provided assets as its elements.
is that an enum too ? Also looks a lot like DatabaseAssetCreator, maybe factor it ?

2023-10-18 19:13 UTC, stilnat commented
> > Partial review, just one question for now :
> > What happen if I change the name of an asset and regenerate the database ?
> 
> Currently nothing, I plan to add cleanup when things are removed.

So does the system still works as expected if doing that ?

2023-10-26 15:37 UTC, joaoburatto commented
> > > Partial review, just one question for now :
> > > What happen if I change the name of an asset and regenerate the database ?
> > 
> > 
> > Currently nothing, I plan to add cleanup when things are removed.
> 
> So does the system still works as expected if doing that ?

It does. The only issue that can happen is unused code.

2023-11-06 23:16 UTC, stilnat commented
the crafting loading bar does not show up when crafting

2023-11-10 17:03 UTC, stilnat commented
Loading asset databases sometimes get stuck and the only way to stop it is to close Unity. need to be fixed. Also it needs to be faster, not instant, but 90 seconds of loading is too long, compared to the current almost instant loading using enums.

2023-11-18 12:10 UTC, stilnat commented
some progress on the pointed issues ?

2023-11-21 18:27 UTC, joaoburatto commented
@stilnat last I checked it was better, but I will still work a little bit to improve it.

2023-12-12 00:20 UTC, stilnat commented
Tried renaming assets, removing them and readding them from database, it seems to work well, crafting, role loadout works well. spawning items too. need to test client.

2023-12-12 00:48 UTC, stilnat requested changes
Partial review, mostly doc for now to add in a few classes

2023-12-12 00:48 UTC, stilnat commented on Assets/Scripts/SS3D/Data/Generated/Bodyparts.cs
should that be removed ?

2023-12-12 00:48 UTC, stilnat commented on Assets/Scripts/SS3D/CodeGeneration/Writers/DatabaseAssetWriter.cs
> +    public class DatabaseAssetWriter
Please add some doc to explain the purpose of this class

2023-12-12 00:48 UTC, stilnat commented on Assets/Scripts/SS3D/CodeGeneration/Writers/StaticClassWriter.cs
> +    public static class StaticClassWriter
Please add some doc to explain the purpose of this class

2023-12-12 18:52 UTC, stilnat requested changes
Looks great, mostly some cosmetic issues, and a bunch of serialized fields to fix due to renaming. Also one script I don't understand the changes the addhand command one.
I still need to test client and perform the following tests : 
-  setup new role loadout.
- create a new database

Prior to merging, doc should be updated to explain to a regular user the following : 
- How to create a new database.
- How to add things in it.
- How to use it in code.

A reference of one of the recipe is broken too but should be easy to fix.

Last thing, this is closing a bounty issue currently evaluated at 10 dollars, I want to reevaluate it at 30 dollars as this is a major rewrite of the asset system.

2023-12-12 18:52 UTC, stilnat commented on Assets/Scripts/SS3D/Data/AssetDatabases/DatabaseAsset.cs
> +        public static implicit operator string(DatabaseAsset asset)
do those have to be created manually ? If this is the case, it'll be important to write it somewhere in the asset doc.

2023-12-12 18:52 UTC, stilnat commented on Assets/Scripts/SS3D/Systems/Audio/AudioSystem.cs
> +        [FormerlySerializedAs("_sfxAudioSourcePrefab")]
Those attributes are pretty garbage, please write down the values there and reput them in if you rename them, instead of using the fields.

2023-12-12 18:52 UTC, stilnat commented on Assets/Scripts/SS3D/Systems/Audio/Boombox.cs
> +        [FormerlySerializedAs("_audioClips")]
same avoid FormerlySerialized fields

2023-12-12 18:52 UTC, stilnat commented on Assets/Scripts/SS3D/Systems/Audio/NoisyCollision.cs
> +        [FormerlySerializedAs("collisionVolume")]
same remove that attribute

2023-12-12 18:52 UTC, stilnat commented on Assets/Scripts/SS3D/Systems/Health/BodyParts/HumanTorso.cs
> +    [FormerlySerializedAs("heart")]
remove formerly serialized

2023-12-12 18:52 UTC, stilnat commented on Assets/Scripts/SS3D/Systems/IngameConsoleSystem/Commands/AddHandCommand.cs
>          public override string Perform(string[] args, NetworkConnection conn)
I'm a bit lost regarding the changes to this one, please explain

2023-12-14 22:20 UTC, joaoburatto commented on Assets/Scripts/SS3D/Systems/Inventory/Items/Item.cs
> -            if(!Enum.TryParse(itemName, out ItemId id))
This check is not needed anymore, as we are not using the enum as the ID anymore, and instead we use a string, not needing a parser.

2023-12-14 22:20 UTC, joaoburatto commented on Assets/Scripts/SS3D/SceneManagement/Editor/SceneSwitcher.cs
> +					EditorSceneUtils.StartScene("sceneEnum");
Good catch, it was like that when I was reworking the system. Fixed now.

2023-12-14 22:20 UTC, joaoburatto commented on Assets/Scripts/SS3D/SceneManagement/Editor/EditorSceneUtils.cs
> +        public static void StartScene(string sceneName)
I think I fixed. But don't focus too much on this, the linting PR will fix it.

2023-12-14 22:20 UTC, joaoburatto commented on Assets/Scripts/SS3D/CodeGeneration/Creators/EnumCreator.cs
> +            enumerable.Insert(0, "None");
If we don't have a None element the first element is the default value. Its standard to create that to prevent unexpected behaviour

2023-12-14 22:20 UTC, joaoburatto commented on Assets/Scripts/SS3D/CodeGeneration/Creators/DatabaseAssetCreator.cs
> +        /// Creates an enum in the object path, with the defined enum name and using a list of provided assets as its elements.
Fixed

2023-12-14 22:20 UTC, joaoburatto commented on Assets/Scripts/SS3D/CodeGeneration/Creators/StaticClassCreator.cs
> +        /// Creates an enum in the object path, with the defined enum name and using a list of provided assets as its elements.
Fixed

2023-12-14 22:20 UTC, joaoburatto commented on Assets/Scripts/SS3D/Systems/IngameConsoleSystem/Commands/AddHandCommand.cs
>          public override string Perform(string[] args, NetworkConnection conn)
Removed because it was unused

2023-12-14 22:20 UTC, joaoburatto commented on Assets/Scripts/SS3D/Systems/Health/BodyParts/HumanTorso.cs
> +    [FormerlySerializedAs("heart")]
done

2023-12-14 22:20 UTC, joaoburatto commented on Assets/Scripts/SS3D/Systems/Audio/Boombox.cs
> +        [FormerlySerializedAs("_audioClips")]
done

2023-12-14 22:20 UTC, joaoburatto commented on Assets/Scripts/SS3D/Systems/Audio/NoisyCollision.cs
> +        [FormerlySerializedAs("collisionVolume")]
done

2023-12-14 22:20 UTC, joaoburatto commented on Assets/Scripts/SS3D/Systems/Audio/AudioSystem.cs
> +        [FormerlySerializedAs("_sfxAudioSourcePrefab")]
done

2023-12-14 22:20 UTC, joaoburatto commented on Assets/Scripts/SS3D/Data/AssetDatabases/DatabaseAsset.cs
> +        public static implicit operator string(DatabaseAsset asset)
Yes, added to the class summary

2023-12-14 22:20 UTC, joaoburatto commented on Assets/Scripts/SS3D/CodeGeneration/Writers/StaticClassWriter.cs
> +    public static class StaticClassWriter
Deleted cause unused

2023-12-14 22:20 UTC, joaoburatto commented on Assets/Scripts/SS3D/CodeGeneration/Writers/DatabaseAssetWriter.cs
> +    public class DatabaseAssetWriter
Added

2023-12-14 22:20 UTC, joaoburatto commented on Assets/Scripts/SS3D/Data/Generated/Bodyparts.cs
Good catch, deleted

2023-12-14 23:00 UTC, stilnat approved these changes

2023-12-14 23:00 UTC, merged