Movable and resizable icons
RE-SS3D/SS3D pull request #1288
Opened 2023-10-18 15:22 UTC by iamteapot422

# Summary
Imports yasirkulas [dynamic panels](https://github.com/yasirkula/UnityDynamicPanels). It's features include:

- Resizable and movable panels with flexible settings
- Docking
- Merging several panels into one
- Icons in names for panels
- API

Dynamic panel prefab is modified to take less space in the header part

https://github.com/RE-SS3D/SS3D/assets/77565416/8efba392-3226-491d-90e0-0fc46afdb586

# Related issues/PRs 
Closes #1222

2023-10-18 17:04 UTC, iamteapot422 commented
Grid's constraint count now changes to fit grid's width

2023-10-19 12:43 UTC, stilnat commented
![image](https://github.com/RE-SS3D/SS3D/assets/14344825/ec2388ef-0fa6-4b1b-b7de-769ff2bed909)

Looks cool but I only ever get an empty windows instead of construction.

2023-10-26 19:25 UTC, stilnat approved these changes, later dismissed
Looks good to me, waiting a bit for John's change before merge

2023-11-02 00:44 UTC, stilnat requested changes
small change and doc

2023-11-02 00:44 UTC, stilnat commented on Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/AssetGridManager.cs
> +public class AssetGridManager : MonoBehaviour
put it into an appropriate namespace and document it a bit more, maybe with an example. You can describe how it act on the construction menu.

2023-11-02 02:57 UTC, cosmiccoincidence commented
Also, merge in master and resolve file conflicts please.

2023-11-02 09:22 UTC, stilnat approved these changes
good work

2023-11-02 09:22 UTC, merged