Directionnal adjacencies
RE-SS3D/SS3D pull request #1303
Opened 2023-11-10 20:17 UTC by stilnat

# Summary

This PR adds directionnals connectables, such as sofas, booths and bench.

#### PR checklist
- [ ] The game builds properly without errors.

- [ ] No unrelated changes are present.

- [ ] No "trash" files are committed.

- [ ] Relevant code is documented.

- [ ] Update the related GitBook document, or create a new one if needed.

# Pictures/Videos)

# Testing

#### Networking checklist

- [ ] Works from host in host mode.

- [ ] Works from server in server mode.

- [ ] Works on server in client mode.

- [ ] Works and is syncronized across different clients.

- [ ] Is persistent.

# Changes

# Related issues/PRs

2023-11-12 06:19 UTC, cosmiccoincidence commented
Are you reusing branches? I've been noticing excessive commits in your PRs lately. It's looks a lot cleaner and is easier to follow from a reviewer's perspective if you do not include not-related commits. Easiest way to do this that I'm aware of is by using a new branch for each PR.

2023-11-12 10:25 UTC, stilnat commented
@cosmiccoincidence some of those branches, I've started not from develop but from other unmerged branches, because I needed what's on those other branches to work with. I thought it's not a big deal because all commits get squashed upon merge in develop, but you're right regarding reviewing. I usually don't review commit by commit myself that's why I did not think about it.
I'll try to find a solution to avoid that, but I'm a bit of a git noob and if you got any clues how to deal with that, that'd be appreciated.

2023-11-12 17:12 UTC, cosmiccoincidence commented
> @cosmiccoincidence some of those branches, I've started not from develop but from other unmerged branches, because I needed what's on those other branches to work with. I thought it's not a big deal because all commits get squashed upon merge in develop, but you're right regarding reviewing. I usually don't review commit by commit myself that's why I did not think about it. I'll try to find a solution to avoid that, but I'm a bit of a git noob and if you got any clues how to deal with that, that'd be appreciated.

Normally I review commit by commit either, but sometimes I do take a quick look at commits for various reasons. For example, let's say I'm checking out the files changed page, and I see human.prefab had been edited, I can find the commit it was changed on and read the title of the commit or commit notes to help me figure out what changed if it wasn't obvious. If course I can look at the prefab in Unity, but sometimes looking at commits does help.

2023-11-12 19:51 UTC, cosmiccoincidence requested changes
Tested it and it worked great from what I've experienced. I'm happy with the performance, any problematic edge cases can be identified in the future. Please add and link documentation for this prior to merge.

2023-11-12 19:51 UTC, cosmiccoincidence commented on Assets/Scripts/SS3D/Systems/Tile/Connections/AdjacencyTypes/DirectionnalShapeResolver.cs
> +    public struct DirectionnalShapeResolver
"Directional" is spelt with a single n. Is the extra n in these script names intentional?

2023-11-12 19:51 UTC, cosmiccoincidence commented on Assets/Content/WorldObjects/Furniture/Generic/Seats/DinnerBooth.prefab
> +%YAML 1.1
- Add collision to this prefab
- Remove cast shadows from this prefab

2023-11-13 19:12 UTC, cosmiccoincidence approved these changes
Amazing work!

2023-11-13 19:13 UTC, merged