Improve console commands
RE-SS3D/SS3D pull request #1354
Opened 2023-11-22 02:57 UTC by iamteapot422

Introduce a couple of methods to remove code repetition and significantly shorten all the commands .

2023-11-23 11:56 UTC, stilnat requested changes
quick review : 
hit body part seems to work okay, I tested it by cutting the right arm and then calling
`hitbodypart HumanHandRightItem(Clone) all toxic 1000`

it destroys it instantly as expected

same test for destroy body part, I get an exception

using command `destroybodypart HumanHandRightItem(Clone)`

```
NullReferenceException: Object reference not set to an instance of an object
SS3D.Systems.IngameConsoleSystem.Commands.Command.ReceiveCheckResponse[T] (System.String[] args, SS3D.Systems.IngameConsoleSystem.Commands.Command+CheckArgsResponse& response, T& calculatedValues) (at Assets/Scripts/SS3D/Systems/IngameConsoleSystem/Commands/Command.cs:67)
SS3D.Systems.IngameConsoleSystem.Commands.DestroyBodyPartCommand.Perform (System.String[] args, FishNet.Connection.NetworkConnection conn) (at Assets/Scripts/SS3D/Systems/IngameConsoleSystem/Commands/DestroyBodyPartCommand.cs:26)
SS3D.Systems.IngameConsoleSystem.CommandsController.RpcLogic___CmdProcessOnlineCommand_161581254 (System.String commandName, System.String[] args, FishNet.Connection.NetworkConnection conn) (at Assets/Scripts/SS3D/Systems/IngameConsoleSystem/CommandsController.cs:127)
```

2023-11-30 19:25 UTC, stilnat requested changes
Tested about half commands on host and 5 or 6 on clients, everything works, code makes sense and reduce a lot the clutter. Please get your branch up to date and it's ready to merge.

2023-11-30 19:25 UTC, stilnat commented on Assets/Scripts/SS3D/Systems/IngameConsoleSystem/Commands/HurtCommand.cs
> +        public override string Usage => "(game object name) (BodyLayerType) (DamageType) (amount of damage)";
change usage to (Player ckey)(Body part name) (body layer name) (damage type) (damage amount)
you can also add an exemple like hurt EditorUser HumanHead all toxic 10

2023-11-30 19:25 UTC, stilnat commented on Assets/Scripts/SS3D/Core/IsExternalInit.cs
Where is that used ?

2023-12-01 01:16 UTC, iamteapot422 commented on Assets/Scripts/SS3D/Core/IsExternalInit.cs
Everywhere with records and inits

2023-12-01 12:53 UTC, stilnat approved these changes
all good, nice stuff, good work

2023-12-01 12:53 UTC, merged