Reimport items
RE-SS3D/SS3D pull request #1376
Opened 2023-12-06 20:44 UTC by cosmiccoincidence

# Summary

- Reimports all current items except clothing cause that kinda goes with the human when we get to updating that again..
- Re-adds the Doodad item.
- Fixes path for clothing items in item asset group.

2023-12-09 12:30 UTC, stilnat requested changes
got some pda issues :
![image](https://github.com/RE-SS3D/SS3D/assets/14344825/e25389df-9097-4e74-8668-e281e7be3a2f)

should the power cell models be the same ? 
![image](https://github.com/RE-SS3D/SS3D/assets/14344825/9b51ffd0-cd83-4d60-b956-c75d03145722)

2023-12-09 12:30 UTC, stilnat commented on Assets/Content/WorldObjects/Items/DoodadTestItem.prefab
What is that for

2023-12-09 19:02 UTC, cosmiccoincidence commented on Assets/Content/WorldObjects/Items/DoodadTestItem.prefab
It's just a test item and is used as an example for correct orientation from blender to Unity. It can also be used as an obvious placeholder mesh for things like tools or weapons. Literally just a test item used in whatever way.
Normally I'm not a fan of these (was originally added by someone else) but I feel that having a single one for Items is fine.

2023-12-09 19:19 UTC, cosmiccoincidence commented
> got some pda issues : [image]
> should the power cell models be the same ? [image]

This seems to a be the same issue. If you look closely in the bottom right of your first screenshot you will notice 2 mugs as well, upon lookin at this, the right one is supposed to be the nuke disk... And it seems that if you try to place one of the prefabs that is clearly broken, the hologram does not appear and no item is placed.

I checked 'develop' to see if the bug is there and it appears it is, but only appears on the nuke disk (2 mugs)..

![Unity_I4UQrdf9kI](https://github.com/RE-SS3D/SS3D/assets/41941008/4a1a4b13-4ffb-4e78-9246-373ad4ca190d)

2023-12-09 20:04 UTC, cosmiccoincidence commented
Fixed the things pointed out, but i merged in master and now have bugs from the examine system since it doesnt seem to be functioning properly.

2023-12-10 11:40 UTC, stilnat approved these changes

2023-12-10 11:40 UTC, merged