Anchor build menu buttons to the top
RE-SS3D/SS3D pull request #1421
Opened 2024-02-01 12:53 UTC by Sjerty

# Summary
Anchor the "Tile search and build" controls to the top of the construction menu

#### PR checklist
- [x] The game builds properly without errors.

- [x] No unrelated changes are present.

- [x] No "trash" files are committed.

# Pictures/Videos
https://youtu.be/n5ZbLStwEW4

# Testing
Start the game and play with the construction menu

#### Networking checklist

- [x] Works from host in host mode.

- [x] Works from server in server mode.

- [x] Works on server in client mode.

- [x] Works and is syncronized across different clients.

# Changes
Moved TileSearchAndBuild menu next under the MainPanel instead of ScrollView, set it's anchor to the top-stretch just as Save/Load buttons, removed it's "Layout element" component, also changed all paddings to 5, adjusted sizes of AssetPanel (parent of ScrollView).

There was a problem however, just moving TileSearchAndBuild in the hierarchy and anchor it, didn't work properly, position of the element just jumped to the bottom of construction menu, to prevent that I created another object (Image), added all TileSearchAndBuild settings to it and set it in place, and everything started to work properly. 
But I don't quite understand why this didn't work with just moving it in hierarchy, maybe some parenting problem?

# Related issues/PRs 
Closes #1402
Closes #1401

2024-02-01 16:47 UTC, cosmiccoincidence commented
> Also if there's a need I can amend this commit with #1401, I just dunno if I should do diff issues in one PR.

Yes, you can do multiple issues in one PR if they are small issues and similar to each other.

2024-02-01 21:50 UTC, stilnat requested changes
One issue is that save and load tabs are affected, ideally, it should not display this darker gray area 

![image](https://github.com/RE-SS3D/SS3D/assets/14344825/b28a6f1b-c5db-48cd-bc8c-af168f7f34df)

2024-02-02 03:21 UTC, Sjerty commented
Made some changes, now there's not so much empty space between Scroll View and Save/Load buttons, but I don't really know if my solution is good enough, bc now menu feels kinda... stretchy?? Not horrible, but still.
I'll just link a video to show how it looks:
https://studio.youtube.com/video/wFVEvI748Aw/edit

2024-02-02 04:15 UTC, Sjerty commented
About #1401, there was already code for the change of color, but id didn't work properly
Also changed "Color" to "Color32", bc after some googling I found out that it works better with HEX (in my case it's one of the two solutions), and regular "Color" works better with values in range of 0-1.

So "Color" just didn't work properly, the color didn't apply to the "Build" button and magenta used in code as 0xA900FF, actually darker than the one right now in the game.
But "Color" will work if you describe it with 0-1 float values such as our blue 0x3132DD = Color(49/255f, 50/255f, 221/255f, 1), so If you want I can change values to that.

2024-02-02 08:59 UTC, stilnat commented
@Sjerty whatever works regarding colors, we don't really have a unified way of dealing with them yet. Your menu looks nice, better than before for sure, I'll take a look at the prefab changes this weekend, github sucks for that.

2024-02-02 09:28 UTC, stilnat commented
So I noticed other issues : 
- The blue color is too dark and very difficult to read, maybe try a lighter one, it's fine if it's not the same as the one from the hologram.
![image](https://github.com/RE-SS3D/SS3D/assets/14344825/282de93b-24f4-45ac-bd86-c738e4203574)

- (maybe not related to this PR) The "load content" game object stays active despite switching between tabs, it should not. It doesn't impact the current display of the menu but might in the future when changes are done on this tab. Need to check if that happen on develop as well.
![image](https://github.com/RE-SS3D/SS3D/assets/14344825/fa2e4617-cf5f-48ed-8020-251ae8a501e6)

2024-02-02 11:41 UTC, Sjerty commented
@stilnat

- Ohhh, no unified approach with colors make it easier xd, I just thought that there's some kind of palette for this, so for that I'll use regular Color, bc Color32 is darker than regular. And I'll shift the colors a bit, so they wouldn't be too bright
How this ones looks for you?
![BuildMenuButtonColors](https://github.com/RE-SS3D/SS3D/assets/56740136/4b783742-588c-42b7-9361-70b4099abfc2)

-Checked the develop branch and "Load Content" game object stay active in there too, I can try and look into this problem and commit into this PR C:

2024-02-02 13:17 UTC, stilnat approved these changes

2024-02-02 13:19 UTC, stilnat approved these changes
all good, better looking menu.

2024-02-02 13:19 UTC, merged