Animation fixes and basic disposals script
RE-SS3D/SS3D pull request #438
Opened 2020-06-27 15:38 UTC by joaoburatto

This PR fixes some animation on the locker, microwave, crates, adds disposals animation for future use, aswell as a sound effect for it

**Known Issues:**
The disposals script doesn't work well yet, the "flush contents" function should just delete everything inside for now but I couldn't figure it out.

2020-06-27 20:39 UTC, Alainx277 commented on Assets/Engine/Inventory/Container.cs
> +
```suggestion
         /// <summary>
        /// Destroys all items inside this container
        /// </summary>
        public void Purge()
        {
            for (var i = 0; i < items.Count; i++)
            {
                var item = items[i].GetComponent<Item>();
                if (item != null)
                {
                    item.container = null;
                }
                ItemHelpers.DestroyItem(item);
            }
        }
```

2020-06-27 22:21 UTC, cosmiccoincidence requested changes
![image](https://user-images.githubusercontent.com/41941008/85933246-e5edc880-b8a2-11ea-8014-d96f282d6764.png)
You need to at least try playtesting your PRs to find this obvious stuff yourself man..

2020-06-27 22:25 UTC, Alainx277 commented
> You need to at least try playtesting your PRs to find this obvious stuff yourself man..

He applied my suggestion directly in Github. So the namespace wasn't imported.

2020-06-27 22:28 UTC, cosmiccoincidence commented
Fair enough, but my point still stands, as there are obvious things in his PRs nearly every time.

2020-06-30 22:05 UTC, cosmiccoincidence approved these changes

2020-06-30 22:05 UTC, merged