Separated game logic from UI views
RE-SS3D/SS3D pull request #571
Opened 2020-09-20 22:01 UTC by Macoron

### Summary
This PR aims to separate game business logic from UI view elements. 

All UI views _(pause panel, Lobby login panel)_ moved to individual prefabs with view controllers components. View controllers communicate with logic by C# events or direct function calls.

All logic elements _(Network Manager, Round Manager)_ also moved to individual prefabs. They don't know anything about UI views. That should greatly reduce spaghetti code in future.

_In future PRs, UI views should be injected with links to logic classes using some Dependency Injection mechanisms. Right now they use singletones/direct links._  

### Known issues

Session restart seems to be broken prior this commit.

2020-09-27 13:03 UTC, Alainx277 requested changes, later dismissed

2020-09-27 13:03 UTC, Alainx277 commented on Assets/Engine/Server/Round/RoundManager.cs
> +        public event System.Action<string> Client_OnTimmerUpdated;
Could you drop the underscore and "On"? So the first one would be "ServerWarmupStarted".

2020-10-03 08:39 UTC, Macoron commented
Should be fixed now

2020-10-16 11:09 UTC, joaoburatto approved these changes
Compiles perfectly.

2020-10-16 11:09 UTC, merged