refactor AdjacencyBitmap to AdjacencyMap without bitwise operations
RE-SS3D/SS3D pull request #873
Opened 2021-12-23 00:54 UTC by Em3rgencyLT

## Summary
This simplifies working with the AdjacencyMap for future additions of different adjacency types. It adds much needed diagonal adjacency support without needing to do hacky workarounds. It also improves readability in several key areas, at the cost of some verboseness. Performance should not be affected much, key changes made were from using bitwise comparisons to a dictionary lookup.

* remove bitwise logic for determining neighbouring tile adjacency
* add diagonal direction support for AdjacencyMap
* fix door.cs not working correctly with tilemap editor
* minor style fixes and cleanup on some touched files

## Changes to Files
Biggest change was converting all the AdjacencyBitmap logic where a byte stored the 8 directions connection information to AdjacencyMap where a Dictionary<Direction, bool> stores it. Everything else was just updating the dependencies that used AdjacencyBitmap before.

## Technical Notes
I chose a dictionary as it seemed the most appropriate structure for the adjacency data. I wanted an IEnumerable for easy filtering with Linq. Additionally directly accessing the values by using a Direction key is much more human readable (if somewhat less efficient) than a byte.

Regarding performance, I didn't perceive any change. Granted ministation is a small map. If this stops being scalable for networking when loading a bigger station, the main way to improve it would be to add areas of concern for clients. IE don't load the whole map, but only some surrounding chunks somewhat outside their view distance.

## Fixes
Closes #865

2021-12-23 12:29 UTC, Em3rgencyLT commented
Test coverage commit: https://github.com/Em3rgencyLT/SS3D/commit/d28d0a5be399622d3c45df156c18b84ad853f726

Will open PR after this merges. Don't want to bloat this PR with it.

2021-12-25 15:53 UTC, stilnat commented
This looks like great work, however, since it affects performances negatively, we should quantify this impact before merging.

2021-12-25 19:40 UTC, Em3rgencyLT commented
> This looks like great work, however, since it affects performances negatively, we should quantify this impact before merging. @Em3rgencyLT I'll try something but if you feel like providing your own tests that would be great !

What would be a satisfactory test? Not really sure how to quantify this sort of thing. If you have an idea i would be grateful if you did it. Additionally, If changes are required don't hesitate to let me know.

2021-12-25 19:42 UTC, Em3rgencyLT commented
As an extra piece of information, i dont think we can keep byte to track adjacency either way. Since for future features, keeping track of each ajacencies type and subtype is also required. My dictionary type will probably change to <Direction, Object>.

2021-12-25 21:38 UTC, stilnat commented
So I ran a few tests on your code, to compare current implementation and yours. My current results are that I can set 7 millions directions in 0.46 seconds with your code and 0.19 with the old one. It's not that bad considering that realistically the number of actual connections updated will be much less at any given time.
However when including initialisation time, the code performs very poorly. 0.23 seconds for 1 million tiles in the old code versus more than 5 seconds for your implementation. 

here's the code : 

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace test_bitwise_operator_vs_dictionnary
{

    public enum Direction
    {
        North = 0,
        NorthEast = 1,
        East = 2,
        SouthEast = 3,
        South = 4,
        SouthWest = 5,
        West = 6,
        NorthWest = 7,
    }
    
    class Program
    {

        static TimeSpan TimeAction(Action blockingAction)
        {
            System.Diagnostics.Stopwatch stopWatch = System.Diagnostics.Stopwatch.StartNew();
            blockingAction();
            stopWatch.Stop();
            return stopWatch.Elapsed;
        }


        static void Main(string[] args)
        {
            int nb = 1000000;

            var elapsed = TimeAction(() =>
            {
                bitwise_test(nb);
            });

            Console.WriteLine("time in bitwise_test " + elapsed);

            var elapsed2 = TimeAction(() =>
            {
                dictionnary_test(nb);     
            });

            Console.WriteLine("time in bitwise_test " + elapsed2);

        }

        static void dictionnary_test(int nb)
        {
            AdjacencyMap[] array1 = new AdjacencyMap[nb];
            for(int i=0; i< nb; i++)
            {
                array1[i] = new AdjacencyMap();
            }


            var elapsed = TimeAction(() =>
            {
                foreach (AdjacencyMap map in array1)
                {
                    map.SetConnection(Direction.NorthEast, true);
                    map.SetConnection(Direction.South, true);
                    map.SetConnection(Direction.West, true);
                    map.SetConnection(Direction.SouthWest, true);
                    map.SetConnection(Direction.West, false);
                    map.SetConnection(Direction.South, false);
                    map.SetConnection(Direction.NorthEast, false);
                }
            });

            Console.WriteLine("time to set connection " + elapsed);
        }

        static void bitwise_test(int nb)
        {

            AdjacencyBitmap[] array1 = new AdjacencyBitmap[nb];
            for (int i = 0; i < nb; i++)
            {
                array1[i] = new AdjacencyBitmap();
            }


            var elapsed = TimeAction(() =>
            {
                foreach (AdjacencyBitmap map in array1)
            {
                map.Connections = AdjacencyBitmap.SetDirection(map.Connections, Direction.NorthEast, true);
                map.Connections = AdjacencyBitmap.SetDirection(map.Connections, Direction.South, true);
                map.Connections = AdjacencyBitmap.SetDirection(map.Connections, Direction.West, true);
                map.Connections = AdjacencyBitmap.SetDirection(map.Connections, Direction.SouthWest, true);
                map.Connections = AdjacencyBitmap.SetDirection(map.Connections, Direction.West, false);
                map.Connections = AdjacencyBitmap.SetDirection(map.Connections, Direction.South, false);
                map.Connections = AdjacencyBitmap.SetDirection(map.Connections, Direction.NorthEast, false);
            }
            });

            Console.WriteLine("time to set connection " + elapsed);
        }

        public class AdjacencyMap
        {
            //Stores a map of which of the 8 surrounding tiles have a connection
            private Dictionary<Direction, bool> connections;

            public AdjacencyMap()
            {
                connections = new Dictionary<Direction, bool>();
                Enum.GetValues(typeof(Direction)).Cast<Direction>().ToList().ForEach(direction =>
                {
                    connections.Add(direction, false);
                });
            }

            public Dictionary<Direction, bool> Connections => connections;

            public bool HasConnection(Direction direction)
            {
                return connections[direction];
            }

            public int GetCardinalConnectionCount()
            {
                return GetAdjacensies().Count;
            }

            public int GetDiagonalConnectionCount()
            {
                return GetAdjacensies().Count;
            }

            /**
             * Gets the direction of the only cardinal/diagonal connection.
             * Assumes there is exactly one cardinal/diagonal connection.
             */
            public Direction GetSingleConnection(bool cardinal = true)
            {
                List<Direction> foundConnections = GetAdjacensies();
                return foundConnections[0];
            }

            /**
             * Get the direction of the only cardinal/diagonal non connection.
             * Assumes there is exactly one cardinal/diagonal non connection
             */
            public Direction GetSingleNonConnection(bool cardinal = true)
            {
                List<Direction> foundConnections = GetAdjacensies();
                List<Direction> directions = CardinalDirections() ;
                List<Direction> missingConnections =
                    directions.Where(direction => !foundConnections.Contains(direction)).ToList();

                return missingConnections[0];
            }

            /**
             * Updates the map, and returns whether there was a change
             */
            public bool SetConnection(Direction direction, bool value)
            {
                bool changed = connections[direction] != value;
                if (changed)
                {
                    connections[direction] = value;
                }

                return changed;
            }

            public bool SetConnections(Dictionary<Direction, bool> newConnections)
            {
                bool changed = !connections.Equals(newConnections);
                connections = newConnections;

                return changed;
            }

            public static List<Direction> CardinalDirections()
            {
                return new List<Direction> { Direction.North, Direction.East, Direction.South, Direction.West };
            }

            private List<Direction> GetAdjacensies()
            {
                List<Direction> directions = CardinalDirections();
                return connections
                    .Where(connection => connection.Value)
                    .Select(connection => connection.Key)
                    .Where(direction => directions.Contains(direction)).ToList();
            }
        }

        public class AdjacencyBitmap
        {
            public struct CardinalInfo
            {
                public int north;
                public int east;
                public int south;
                public int west;
                public int numConnections;

                public CardinalInfo(byte bitmap)
                {
                    north = Adjacent(bitmap, Direction.North);
                    east = Adjacent(bitmap, Direction.East);
                    south = Adjacent(bitmap, Direction.South);
                    west = Adjacent(bitmap, Direction.West);

                    numConnections = north + east + south + west;
                }

                /**
                 * Gets the direction of the only positive connection.
                 * Assumes there is exactly one positive connection
                 */
                public Direction GetOnlyPositive()
                {
                    r [...]

2021-12-25 22:05 UTC, Em3rgencyLT commented
Thank you for taking the time to do this @stilnat. This seems thorough and lifts the burden off me. What do you mean by 'including initialization'? Is that the time taken for memory allocation for the dictionaries or what?

Either way, a million tiles is a 1000x1000 station. Which is... Possible. The decision to be made then is - is 5 seconds+ an acceptable load time for such a station. Assuming we won't be chunking it and every player needs to load the entire thing.

Additionally, what is the alternative? Like I mentioned above, we need to begin tracking adjacency type and subtype for each connection. Is that something that we want to encode into bytes as well?

2021-12-26 11:40 UTC, Em3rgencyLT commented
Updated to use Array instead of Dictionary. Updated PR description. Re-ran the tests. Test code:
```
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace adjacencyMap
{
    public enum Direction
    {
        North = 0,
        NorthEast = 1,
        East = 2,
        SouthEast = 3,
        South = 4,
        SouthWest = 5,
        West = 6,
        NorthWest = 7,
    }
    
    public struct AdjacencyData
    {
        public AdjacencyData(string genericType, string specificType, bool exists)
        {
            GenericType = genericType;
            SpecificType = specificType;
            Exists = exists;
        }

        public string GenericType;
        public string SpecificType;
        public bool Exists;

        public override bool Equals(object other)
        {
            return other is AdjacencyData otherData && GenericType == otherData.GenericType && SpecificType == otherData.SpecificType &&
                   Exists == otherData.Exists;
        }
    }
    
    internal class Program
    {
        static TimeSpan TimeAction(Action blockingAction)
        {
            System.Diagnostics.Stopwatch stopWatch = System.Diagnostics.Stopwatch.StartNew();
            blockingAction();
            stopWatch.Stop();
            return stopWatch.Elapsed;
        }
        
        public static void Main(string[] args)
        {
            int nb = 1000000;

            var elapsed = TimeAction(() =>
            {
                bitwise_test(nb);
            });

            Console.WriteLine("time in bitwise_test " + elapsed);

            var elapsed2 = TimeAction(() =>
            {
                array_test(nb);     
            });

            Console.WriteLine("time in array_test " + elapsed2);
        }
        
         static void array_test(int nb)
        {
            AdjacencyMap[] array1 = new AdjacencyMap[nb];
            for(int i=0; i< nb; i++)
            {
                array1[i] = new AdjacencyMap();
            }
            
            var elapsed = TimeAction(() =>
            {
                foreach (AdjacencyMap map in array1)
                {
                    map.SetConnection(Direction.NorthEast, new AdjacencyData("", "", true));
                    map.SetConnection(Direction.South, new AdjacencyData("", "", true));
                    map.SetConnection(Direction.West, new AdjacencyData("", "", true));
                    map.SetConnection(Direction.SouthWest, new AdjacencyData("", "", true));
                    map.SetConnection(Direction.West, new AdjacencyData("", "", false));
                    map.SetConnection(Direction.South, new AdjacencyData("", "", false));
                    map.SetConnection(Direction.NorthEast, new AdjacencyData("", "", false));
                }
            });

            Console.WriteLine("time to set array connection " + elapsed);
        }

        static void bitwise_test(int nb)
        {

            AdjacencyBitmap[] array1 = new AdjacencyBitmap[nb];
            for (int i = 0; i < nb; i++)
            {
                array1[i] = new AdjacencyBitmap();
            }


            var elapsed = TimeAction(() =>
            {
                foreach (AdjacencyBitmap map in array1)
            {
                map.Connections = AdjacencyBitmap.SetDirection(map.Connections, Direction.NorthEast, true);
                map.Connections = AdjacencyBitmap.SetDirection(map.Connections, Direction.South, true);
                map.Connections = AdjacencyBitmap.SetDirection(map.Connections, Direction.West, true);
                map.Connections = AdjacencyBitmap.SetDirection(map.Connections, Direction.SouthWest, true);
                map.Connections = AdjacencyBitmap.SetDirection(map.Connections, Direction.West, false);
                map.Connections = AdjacencyBitmap.SetDirection(map.Connections, Direction.South, false);
                map.Connections = AdjacencyBitmap.SetDirection(map.Connections, Direction.NorthEast, false);
            }
            });

            Console.WriteLine("time to set bitwise connection " + elapsed);
        }
        
        public class AdjacencyMap
    {
        //Stores an array of which of the 8 surrounding tiles have a connection. Order assumed to match Direction enum values.
        private AdjacencyData[] connections;

        public AdjacencyMap()
        {
            connections = new [] {
                new AdjacencyData ("", "", false),
                new AdjacencyData ("", "", false),
                new AdjacencyData ("", "", false),
                new AdjacencyData ("", "", false),
                new AdjacencyData ("", "", false),
                new AdjacencyData ("", "", false),
                new AdjacencyData ("", "", false),
                new AdjacencyData ("", "", false),
            };
        }

        /**
         * Updates the map, and returns whether there was a change
         */
        public bool SetConnection(Direction direction, AdjacencyData data)
        {
            bool changed = !data.Equals(connections[(int) direction]);
            if (changed)
            {
                connections[(int) direction] = data;
            }

            return changed;
        }

        public override string ToString()
        {
            return $"{connections}";
        }
    }
        
         public class AdjacencyBitmap
        {
            public struct CardinalInfo
            {
                public int north;
                public int east;
                public int south;
                public int west;
                public int numConnections;

                public CardinalInfo(byte bitmap)
                {
                    north = Adjacent(bitmap, Direction.North);
                    east = Adjacent(bitmap, Direction.East);
                    south = Adjacent(bitmap, Direction.South);
                    west = Adjacent(bitmap, Direction.West);

                    numConnections = north + east + south + west;
                }
            }

            /**
         * Returns a bitmap which modifies the input bitmap so that
         * the bit corresponding to the given direction is set to the given value.
         */
            public static byte SetDirection(byte bitmap, Direction direction, bool value)
            {
                // Set the direction bit to isConnected (1 or 0)
                byte output = bitmap;
                output &= (byte)~(1 << (int)direction);
                output |= (byte)((value ? 1 : 0) << (int)direction);

                return output;
            }

            public byte Connections { get; set; } = 0;


            public static int Adjacent(byte bitmap, Direction direction)
            {
                return (bitmap >> (int)direction) & 0x1;
            }
        }
    }
}```

2021-12-26 16:04 UTC, stilnat commented on Assets/Engine/Tile/TileRework/Connections/AdjacencyMap.cs
> +        private List<Direction> GetAdjacensies(bool cardinal)
could you rename it in GetAdjacencies ?

2021-12-26 16:24 UTC, stilnat requested changes
Great work ! On my side I'll be happy to accept the changes, there's just a small english typo to correct with "GetAdjacensies" :) .

2021-12-26 17:54 UTC, Em3rgencyLT commented
Done

2021-12-27 09:31 UTC, stilnat approved these changes
Great work ! This make a solid base to work on future connectors, everything checks out !

2021-12-27 09:31 UTC, merged