Make inventory UI great again
RE-SS3D/SS3D pull request #940
Opened 2022-12-18 15:10 UTC by stilnat

## Summary

Adds a functionning UI for the hands, and some placeholder for the ID, Bags, and pockets.
Reintroduce the sprite generator.
Make a few small cosmetic changes on the Inventory UI (rotation, outliner, spacing, size...).

## Pictures/Videos (optional)

![image](https://user-images.githubusercontent.com/14344825/208305761-ef805c83-fddb-481c-90a1-8b57592f39e2.png)

## Technical Notes (optional)

No major changes. The main change is that Inventory is now activating inventoryUI.

## Known issues

- The hands can't be switched by clicking on the icons like on the outdated branch. This can be solved in a different PR.
- The sprite are kind of ugly, could be due to the shader, maybe that can also be part of another PR.

## Fixes (optional)

Closes #935 
Closes #939

2022-12-30 03:18 UTC, cosmiccoincidence commented
> bring an item from one hand over to the other and that item's ui pretty much breaks and you can't drag anything anymore. - LightVelox

Seems there seems to be some bugs. Is that due to lack of container functionality or a problem with the UI itself?

2023-01-01 18:32 UTC, stilnat commented
> > bring an item from one hand over to the other and that item's ui pretty much breaks and you can't drag anything anymore. - LightVelox
> 
> Seems there seems to be some bugs. Is that due to lack of container functionality or a problem with the UI itself?

I'll check that as soon as I can get in game again, I have a bunch of assembly errors right now

2023-01-01 19:06 UTC, stilnat commented
@cosmiccoincidence Where did you see LightVelox comment ? I would have missed it if you didn't cite it

2023-01-02 06:26 UTC, Ryan089 commented
@stilnat it was in the #pull-requests channel [here](https://discord.com/channels/483813139633143808/483814334770839573/1058220429321457766).

2023-01-03 13:42 UTC, TaylorNAlbarnaz requested changes
You should only be able to drag items with your Left Mouse Button, currently you can drag using the Right Mouse Button as well

2023-01-03 18:57 UTC, stilnat commented
Don't accept this PR yet, it's not working client side, only host side

2023-01-03 19:19 UTC, stilnat commented
Nevermind, the bug is only in the client when client is in editor

2023-01-07 23:08 UTC, joaoburatto requested changes

2023-01-07 23:08 UTC, joaoburatto commented on Assets/Scripts/SS3D/Systems/Storage/Containers/AttachedContainer.cs
> +                    item.Unfreeze();
it is preferred to add braces

2023-01-07 23:08 UTC, joaoburatto commented on Assets/Scripts/SS3D/Systems/Storage/Containers/Hands.cs
> +        public HandsUi HandsUI {get; private set;}
add space before get and after set;

2023-01-07 23:08 UTC, joaoburatto commented on Assets/Scripts/SS3D/Systems/Storage/Items/Item.cs
> +
Remove empty space

2023-01-07 23:08 UTC, joaoburatto commented on Assets/Scripts/SS3D/Systems/Storage/Items/Item.cs
> +
Remove empty space

2023-01-07 23:08 UTC, joaoburatto commented on Assets/Scripts/SS3D/Systems/Storage/UI/ItemDisplay.cs
> +            if(eventData.button != PointerEventData.InputButton.Left) return;
add space after if

2023-01-09 01:32 UTC, stilnat commented
The UI is now working on any player, client or host.

2023-01-09 02:18 UTC, TaylorNAlbarnaz approved these changes
The problem was properly fixed and it works as expected now

2023-01-09 02:19 UTC, merged