Gamemode System: Group Objectives
RE-SS3D/SS3D pull request #943
Opened 2022-12-30 07:02 UTC by Ryan089

## Summary

This PR allows for group objectives to be created by setting the appropriate Collaboration Type on the objective definition:
- **Individual**: relevant only to the player.
- **Cooperative**: once one player succeeds, all other assignees succeed.
- **Competitive**: once one player succeeds, all other assignees fail.

## Changes to Files

- **GamemodeTests.cs** added new tests to confirm the competitive and cooperative objective functionality, and confirm late join functionality. Minor tweaks to other tests were included to aid maintainability.
- **GamemodeObjective.cs** added fields for the collaboration type, and amount of objective assignees. *Note: Alignment requirement is currently unused*.
- **Gamemode.cs** separated the creation of round start objectives from the assignment of those objectives, and manages finalization of shared objectives.
- **ObjectiveFactory.cs** allows easier access to objective creation and duplication.
- **GetItemObjective.cs** replaces **GetNukeCardObjective.cs** by providing a generic means of creating objectives where a specific item must be found.
- **GamemodeObjectiveItemView.cs** changes the view colours to distinguish "In Progress" objectives (yellow) from "Failed" objectives (red).

2023-01-03 23:29 UTC, joaoburatto requested changes

2023-01-03 23:29 UTC, joaoburatto commented on Assets/Scripts/EditorTests/GamemodeTests.cs
> +
remove blank space

2023-01-03 23:29 UTC, joaoburatto commented on Assets/Scripts/EditorTests/GamemodeTests.cs
> +
remove blank space

2023-01-03 23:29 UTC, joaoburatto commented on Assets/Scripts/EditorTests/GamemodeTests.cs
remove blank space

2023-01-03 23:29 UTC, joaoburatto commented on Assets/Scripts/EditorTests/GamemodeTests.cs
> +
remove blank space

2023-01-03 23:29 UTC, joaoburatto commented on Assets/Scripts/EditorTests/GamemodeTests.cs
> +
remove blank space

2023-01-03 23:29 UTC, joaoburatto commented on Assets/Scripts/SS3D/Systems/Gamemodes/GamemodeObjective.cs
> +            this._title = title;
remove all this.variable, if the variable is private, it'll have the _ on it, so there's no reason to use this.variable.

2023-01-03 23:29 UTC, joaoburatto commented on Assets/Scripts/SS3D/Systems/Gamemodes/Modes/Gamemode.cs
> +        protected virtual void AssignRoundStartObjectives(List<string> CKeysToAssign)
CkeysToAssign should start with a lower letter, as in "ckeyToAssign"

2023-01-03 23:29 UTC, joaoburatto commented on Assets/Scripts/SS3D/Systems/Gamemodes/Modes/Gamemode.cs
> +        private void CreateRoundStartObjectives(int numberToCreate)
rename numberToCreate to amountToCreate

2023-01-03 23:29 UTC, joaoburatto commented on Assets/Scripts/SS3D/Systems/Gamemodes/Modes/Gamemode.cs
> +            if (!triggerObjective.Succeeded) return;
join both ifs

2023-01-03 23:29 UTC, joaoburatto commented on Assets/Scripts/SS3D/Systems/Gamemodes/ObjectiveFactory.cs
> +
remove blank space

2023-01-05 14:54 UTC, TaylorNAlbarnaz requested changes
Clients can't complete objectives
Clients also don't have their objectives set as complete when the hosts completes them, though they might be user-specific and not shared here, but they should fail if that's the case

2023-01-06 03:28 UTC, TaylorNAlbarnaz approved these changes
lgtm

2023-01-06 03:29 UTC, merged